apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: highpay
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
    - host: highpay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8081
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8081
          - path: /v3
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8081
    - host: grafana.highpay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: prometheus.highpay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
