apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: highpay

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - provider-simulator.yaml
  - payment-service.yaml
  - payment-processor.yaml
  - frontend.yaml
  - prometheus.yaml
  - grafana.yaml
  - hpa.yaml
  - ingress.yaml
