apiVersion: v1
kind: Secret
metadata:
  name: highpay-secrets
type: Opaque
stringData:
  postgres-db: highpay
  postgres-user: highpay
  postgres-password: change_me_postgres_password
  rabbitmq-user: highpay
  rabbitmq-password: change_me_rabbitmq_password
  internal-auth-token: change_me_internal_auth_token
  public-jwt-secret: change_me_public_jwt_secret_with_at_least_32_chars
  grafana-admin-user: admin
  grafana-admin-password: change_me_grafana_password
